#ifndef CONFIG_H
#define CONFIG_H

#define TERRAIN_SIZE 400
#define TERRAIN_SCALE 4.0f
#define MAX_TERRAIN_HEIGHT 100

#define RANDOM_TERRAIN true

#define TREE_COUNT 200

#define WORLD_SIZE TERRAIN_SIZE * TERRAIN_SCALE

#endif // CONFIG_H
