#ifndef CONFIG_H
#define CONFIG_H

#define TERRAIN_SIZE 150
#define TERRAIN_SCALE 4.0f
#define MAX_TERRAIN_HEIGHT 100

#define RANDOM_TERRAIN true

#define CHUNK_RADIUS 1
#define CHUNK_DIAMETER CHUNK_RADIUS * 2 + 1
#define TREE_COUNT 50

#define WORLD_SIZE TERRAIN_SIZE * TERRAIN_SCALE

#endif // CONFIG_H
